Use pip-tools to pin dependencies of pip-tools
There was an API change in click that causes an error like
`TypeError: __init__() got an unexpected keyword argument 'show_envvar'`
upgrading click to version 7 solves the problem see
<https://github.com/pypa/pipenv/issues/3552>